name: Manage Labels

on: push

jobs:
  labeler:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Run Labeler
        if: success()
        uses: crazy-max/ghaction-github-labeler@v3.1.1
        with:
          yaml_file: .github/labels.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
